name: deep-audio
channels:
  - conda-forge
dependencies:
  - ffmpeg
  - huggingface_hub
  - ipykernel
  - jupyter
  - librosa
  - libsndfile
  - matplotlib
  - numpy<2
  - pandas
  - pip
  - pyarrow
  - python=3.11
  - python-dotenv
  - pytorch>=2.4
  - scikit-learn
  - scipy
  - seaborn
  - torchaudio
  - torchvision
  - transformers
  - pip:
    - accelerate==1.14.0
    - aliyun-python-sdk-core==2.16.0
    - aliyun-python-sdk-kms==2.16.5
    - antlr4-python3-runtime==4.9.3
    - asteroid-filterbanks==0.4.0
    - audiomentations==0.43.1
    - crcmod==1.7
    - cryptography==49.0.0
    - editdistance==0.8.1
    - funasr==1.3.9
    - hydra-core==1.3.3
    - jaconv==0.5.0
    - jamo==0.4.1
    - jieba==0.42.1
    - jmespath==0.10.0
    - joblib==1.5.3
    - kaldiio==2.18.1
    - modelscope==1.37.1
    - narwhals==2.22.1
    - numpy==1.26.4
    - numpy-minmax==0.5.0
    - numpy-rms==0.6.0
    - omegaconf==2.3.1
    - oss2==2.19.1
    - protobuf==7.35.1
    - pycryptodome==3.23.0
    - pynndescent==0.6.0
    - python-stretch==0.3.1
    - scipy==1.17.1
    - sentencepiece==0.2.1
    - tensorboardX==2.6.5
    - threadpoolctl==3.6.0
    - tiktoken==0.13.0
    - torch-complex==0.4.4
    - umap-learn==0.5.12
